import type { MaybePromise } from "bun";
import type { MiniGlobalStyles, MiniScripts } from "../internal/mini/types";
import type { MiniContext, MiniHead } from "./shared";

/** HTMX loading strategy configured for the MiniFW document. */
export type MiniHtmxConfig =
  | {
      type: "cdn";
      /** The HTMX semver string or major version number, e.g. `"4.0.0"`. */
      version: string | number;
    }
  | {
      type: "local";
      /** Returns the raw HTMX source to inline. */
      loadFn: () => MaybePromise<string>;
    };

/** Arguments received by the optional document head renderer. */
export type MiniDocumentHeadArguments = {
  context: MiniContext;
  /** Metadata supplied by the matched page. */
  head?: MiniHead;
};

/** Configuration for the HTML document generated by {@link mini}. */
export type MiniDocumentOptions = {
  /** Attributes written on the generated `<html>` element. */
  htmlAttributes?: Record<string, string | undefined>;
  /** Attributes written on the generated `<body>` element. */
  bodyAttributes?: Record<string, string | undefined>;
  /** Additional tags written into the generated `<head>`. */
  head?: (arguments_: MiniDocumentHeadArguments) => MaybePromise<string>;
};

/** Document and browser behavior owned by {@link mini}. */
export type MiniConfig = {
  /** Configuration for MiniFW's generated document scaffold. */
  document?: MiniDocumentOptions;
  /** HTMX loading configuration. Set to `false` to omit HTMX. */
  htmx?: MiniHtmxConfig | false;
  /** Enables MiniFW's runtime for promoted scoped styles. Defaults to `true`. */
  runtime?: boolean;
  /** Global CSS included in full-page documents. */
  globalStyles?: MiniGlobalStyles;
  /** Global scripts included in full-page documents. */
  scripts?: MiniScripts;
};
